FROM node:22-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN npm i -g pnpm

COPY package.json ./

RUN pnpm install --no-frozen-lockfile

COPY . .

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium

RUN pnpm exec playwright install --with-deps chromium

CMD ["pnpm", "storybook:docker"]
