FROM node:22-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN npm i -g pnpm@9.15.0

COPY package.json ./

RUN pnpm install --no-frozen-lockfile

COPY . .

RUN pnpm exec playwright install --with-deps chromium

CMD ["pnpm", "storybook:docker"]
