/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export interface GoShishaBackendInternalModelsUpdateUserInput {
  /** 自己紹介文（省略可） */
  description?: string;
  /** 表示名（省略可） */
  display_name?: string;
  /** 外部URL（省略可、http(s)://...のみ許可） */
  external_url?: string;
  /** アイコン画像URL（省略可、/images/... または http(s)://...） */
  icon_url?: string;
}
