/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import type { GoShishaBackendInternalModelsValidationErrorError } from "./goShishaBackendInternalModelsValidationErrorError";

/**
 * 入力値のバリデーションに失敗した場合のエラーレスポンス
 */
export interface GoShishaBackendInternalModelsValidationError {
  /** エラー種別の識別子 */
  error?: GoShishaBackendInternalModelsValidationErrorError;
}
