/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export interface GoShishaBackendInternalModelsErrorResponse {
  error?: string;
}
