/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export interface GoShishaBackendInternalModelsUser {
  description?: string;
  display_name?: string;
  email?: string;
  external_url?: string;
  icon_url?: string;
  id?: number;
}
