/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import type { GoShishaBackendInternalModelsForbiddenErrorError } from "./goShishaBackendInternalModelsForbiddenErrorError";

/**
 * 権限がない操作を実行した場合のエラーレスポンス
 */
export interface GoShishaBackendInternalModelsForbiddenError {
  /** エラー種別の識別子 */
  error: GoShishaBackendInternalModelsForbiddenErrorError;
}
