/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

/**
 * エラー種別の識別子
 */
export type GoShishaBackendInternalModelsConflictErrorError =
  (typeof GoShishaBackendInternalModelsConflictErrorError)[keyof typeof GoShishaBackendInternalModelsConflictErrorError];

export const GoShishaBackendInternalModelsConflictErrorError = {
  email_already_exists: "email_already_exists",
  already_liked: "already_liked",
  not_liked: "not_liked",
} as const;
