/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

/**
 * サーバー内部でエラーが発生した場合のエラーレスポンス
 */
export interface GoShishaBackendInternalModelsServerError {
  /** エラー種別の識別子 */
  error?: string;
  /** ユーザー向けのエラーメッセージ */
  message?: string;
}
