/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

/**
 * エラー種別の識別子
 */
export type GoShishaBackendInternalModelsValidationErrorError =
  (typeof GoShishaBackendInternalModelsValidationErrorError)[keyof typeof GoShishaBackendInternalModelsValidationErrorError];

export const GoShishaBackendInternalModelsValidationErrorError = {
  validation_failed: "validation_failed",
} as const;
