/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export interface GoShishaBackendInternalModelsUpdateSlideInput {
  /** フレーバーID。省略または null を指定するとフレーバーが解除される */
  flavor_id?: number;
  /** 更新対象のスライドID */
  id: number;
  /** スライドのテキスト。省略すると空文字で上書きされる */
  text?: string;
}
