/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import type { GoShishaBackendInternalModelsUpdateSlideInput } from "./goShishaBackendInternalModelsUpdateSlideInput";

export interface GoShishaBackendInternalModelsUpdatePostInput {
  /**
   * @minItems 1
   * @maxItems 10
   */
  slides: GoShishaBackendInternalModelsUpdateSlideInput[];
}
