/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import type { GoShishaBackendInternalModelsNotFoundErrorError } from "./goShishaBackendInternalModelsNotFoundErrorError";

/**
 * リソースが見つからない場合のエラーレスポンス
 */
export interface GoShishaBackendInternalModelsNotFoundError {
  /** エラー種別の識別子 */
  error: GoShishaBackendInternalModelsNotFoundErrorError;
}
