/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

/**
 * エラー種別の識別子
 */
export type GoShishaBackendInternalModelsForbiddenErrorError =
  (typeof GoShishaBackendInternalModelsForbiddenErrorError)[keyof typeof GoShishaBackendInternalModelsForbiddenErrorError];

export const GoShishaBackendInternalModelsForbiddenErrorError = {
  forbidden: "forbidden",
} as const;
