/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import type { GoShishaBackendInternalModelsConflictErrorError } from "./goShishaBackendInternalModelsConflictErrorError";

/**
 * リソース競合エラーレスポンス（メール重複・いいね重複・いいね未実施など）
 */
export interface GoShishaBackendInternalModelsConflictError {
  /** エラー種別の識別子 */
  error: GoShishaBackendInternalModelsConflictErrorError;
}
