/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export type PostPostsIdUnlike404 = { [key: string]: unknown };
