/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */

export type PostAuthRefresh200 = { [key: string]: string };
