name: 機能実装
description: 新機能の開発やエンハンスメント
title: "[Feature] "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 機能概要
      description: 実装したい機能の概要を記載してください。
      placeholder: 例：投稿にタグ機能を追加したい
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 対象範囲
      description: 主にどの部分の機能実装ですか？
      options:
        - Frontend（コンポーネント・フック）
        - Backend（API・サービス・ハンドラー）
        - Database（スキーマ・マイグレーション）
        - 全スタック（Frontend + Backend + DB）
        - インフラ（Docker・CI/CD・デプロイ）
        - 共通（型定義・ユーティリティ）
        - テスト（単体・結合・E2E）
        - その他
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: 対象外範囲
      description: 今回の機能実装では対象外とする範囲を明記してください。
      placeholder: |
        例：
        - 管理者機能は対象外
        - モバイル対応は別Issue
        - パフォーマンス最適化は後回し
        - 外部API連携は含まない
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: 背景・動機
      description: なぜこの機能が必要なのか、ユーザーにどんな価値を提供するかを記載してください。
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したとみなす条件を箇条書きで記載してください。
      placeholder: |
        - [ ] ユーザーが投稿にタグを追加できる
        - [ ] タグで投稿を絞り込み検索できる
        - [ ] タグの一覧表示ができる
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: 技術的な考慮事項
      description: 実装時に考慮すべき技術的な要素があれば記載してください。
      placeholder: 例：API設計、データベーススキーマ変更、パフォーマンス要件など
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: その他・備考
      description: 補足情報や参考資料があれば記載してください。
    validations:
      required: false