// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/illionillion/go-shisha"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/posts": {
            "get": {
                "description": "全ての投稿の一覧を取得します（総数付き）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿一覧取得",
                "responses": {
                    "200": {
                        "description": "投稿一覧と総数",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.PostsResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "新しい投稿を作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿作成",
                "parameters": [
                    {
                        "description": "投稿情報",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.CreatePostInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成された投稿",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.Post"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "指定されたIDの投稿情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿詳細取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "投稿ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "投稿情報",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.Post"
                        }
                    },
                    "400": {
                        "description": "無効な投稿ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "投稿が見つかりません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/posts/{id}/like": {
            "post": {
                "description": "指定された投稿にいいねを追加します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿にいいね",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "投稿ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "いいねが追加された投稿",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.Post"
                        }
                    },
                    "400": {
                        "description": "無効な投稿ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "投稿が見つかりません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/posts/{id}/unlike": {
            "post": {
                "description": "指定された投稿のいいねを取り消します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "投稿のいいねを取り消す",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "投稿ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "いいねが取り消された投稿",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.Post"
                        }
                    },
                    "400": {
                        "description": "無効な投稿ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "投稿が見つかりません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "全てのユーザーの一覧を取得します（総数付き）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー一覧取得",
                "responses": {
                    "200": {
                        "description": "ユーザー一覧と総数",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.UsersResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "指定されたIDのユーザー情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー詳細取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー情報",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.User"
                        }
                    },
                    "400": {
                        "description": "無効なユーザーID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}/posts": {
            "get": {
                "description": "指定されたユーザーの全ての投稿を取得します（総数付き）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザーの投稿一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "投稿一覧と総数",
                        "schema": {
                            "$ref": "#/definitions/go-shisha-backend_internal_models.PostsResponse"
                        }
                    },
                    "400": {
                        "description": "無効なユーザーID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-shisha-backend_internal_models.CreatePostInput": {
            "type": "object",
            "required": [
                "message",
                "user_id"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "maxLength": 100
                },
                "slides": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-shisha-backend_internal_models.Slide"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "go-shisha-backend_internal_models.Flavor": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "go-shisha-backend_internal_models.Post": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_liked": {
                    "type": "boolean"
                },
                "likes": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "slides": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-shisha-backend_internal_models.Slide"
                    }
                },
                "user": {
                    "$ref": "#/definitions/go-shisha-backend_internal_models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "go-shisha-backend_internal_models.PostsResponse": {
            "type": "object",
            "properties": {
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-shisha-backend_internal_models.Post"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-shisha-backend_internal_models.Slide": {
            "type": "object",
            "properties": {
                "flavor": {
                    "$ref": "#/definitions/go-shisha-backend_internal_models.Flavor"
                },
                "image_url": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "go-shisha-backend_internal_models.User": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "external_url": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "go-shisha-backend_internal_models.UsersResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-shisha-backend_internal_models.User"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Go-Shisha API",
	Description:      "シーシャSNSアプリケーションのバックエンドAPI\nこのAPIはシーシャの投稿、ユーザー管理を行います",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
