/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { apiFetch } from "../lib/api-client";
import type {
  GoShishaBackendInternalModelsAuthResponse,
  GoShishaBackendInternalModelsCreateUserInput,
  GoShishaBackendInternalModelsErrorResponse,
  GoShishaBackendInternalModelsLoginInput,
  PostAuthLogout200,
  PostAuthRefresh200,
} from "./model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * メールアドレスとパスワードでログインし、JWT（Cookie）を発行する
 * @summary ログイン
 */
export type postAuthLoginResponse200 = {
  data: GoShishaBackendInternalModelsAuthResponse;
  status: 200;
};

export type postAuthLoginResponse400 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 400;
};

export type postAuthLoginResponse401 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 401;
};

export type postAuthLoginResponse500 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 500;
};

export type postAuthLoginResponseSuccess = postAuthLoginResponse200 & {
  headers: Headers;
};
export type postAuthLoginResponseError = (
  | postAuthLoginResponse400
  | postAuthLoginResponse401
  | postAuthLoginResponse500
) & {
  headers: Headers;
};

export type postAuthLoginResponse = postAuthLoginResponseSuccess | postAuthLoginResponseError;

export const getPostAuthLoginUrl = () => {
  return `/auth/login`;
};

export const postAuthLogin = async (
  goShishaBackendInternalModelsLoginInput: GoShishaBackendInternalModelsLoginInput,
  options?: RequestInit
): Promise<postAuthLoginResponse> => {
  return apiFetch<postAuthLoginResponse>(getPostAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(goShishaBackendInternalModelsLoginInput),
  });
};

export const getPostAuthLoginMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: GoShishaBackendInternalModelsLoginInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: GoShishaBackendInternalModelsLoginInput },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: GoShishaBackendInternalModelsLoginInput }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>;
export type PostAuthLoginMutationBody = GoShishaBackendInternalModelsLoginInput;
export type PostAuthLoginMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ログイン
 */
export const usePostAuthLogin = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data: GoShishaBackendInternalModelsLoginInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: GoShishaBackendInternalModelsLoginInput },
  TContext
> => {
  return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
};
/**
 * Cookieを削除し、Refresh Tokenを無効化する
 * @summary ログアウト
 */
export type postAuthLogoutResponse200 = {
  data: PostAuthLogout200;
  status: 200;
};

export type postAuthLogoutResponse401 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 401;
};

export type postAuthLogoutResponse500 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 500;
};

export type postAuthLogoutResponseSuccess = postAuthLogoutResponse200 & {
  headers: Headers;
};
export type postAuthLogoutResponseError = (
  | postAuthLogoutResponse401
  | postAuthLogoutResponse500
) & {
  headers: Headers;
};

export type postAuthLogoutResponse = postAuthLogoutResponseSuccess | postAuthLogoutResponseError;

export const getPostAuthLogoutUrl = () => {
  return `/auth/logout`;
};

export const postAuthLogout = async (options?: RequestInit): Promise<postAuthLogoutResponse> => {
  return apiFetch<postAuthLogoutResponse>(getPostAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostAuthLogoutMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationKey = ["postAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
    return postAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>;

export type PostAuthLogoutMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ログアウト
 */
export const usePostAuthLogout = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
};
/**
 * 認証されたユーザーの情報を取得する
 * @summary 現在のユーザー情報取得
 */
export type getAuthMeResponse200 = {
  data: GoShishaBackendInternalModelsAuthResponse;
  status: 200;
};

export type getAuthMeResponse401 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 401;
};

export type getAuthMeResponse500 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 500;
};

export type getAuthMeResponseSuccess = getAuthMeResponse200 & {
  headers: Headers;
};
export type getAuthMeResponseError = (getAuthMeResponse401 | getAuthMeResponse500) & {
  headers: Headers;
};

export type getAuthMeResponse = getAuthMeResponseSuccess | getAuthMeResponseError;

export const getGetAuthMeUrl = () => {
  return `/auth/me`;
};

export const getAuthMe = async (options?: RequestInit): Promise<getAuthMeResponse> => {
  return apiFetch<getAuthMeResponse>(getGetAuthMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAuthMeQueryKey = () => {
  return [`/auth/me`] as const;
};

export const getGetAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) =>
    getAuthMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>;
export type GetAuthMeQueryError = GoShishaBackendInternalModelsErrorResponse;

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 現在のユーザー情報取得
 */

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Refresh Tokenを使って新しいAccess Tokenを発行する
 * @summary アクセストークンのリフレッシュ
 */
export type postAuthRefreshResponse200 = {
  data: PostAuthRefresh200;
  status: 200;
};

export type postAuthRefreshResponse401 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 401;
};

export type postAuthRefreshResponse500 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 500;
};

export type postAuthRefreshResponseSuccess = postAuthRefreshResponse200 & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (
  | postAuthRefreshResponse401
  | postAuthRefreshResponse500
) & {
  headers: Headers;
};

export type postAuthRefreshResponse = postAuthRefreshResponseSuccess | postAuthRefreshResponseError;

export const getPostAuthRefreshUrl = () => {
  return `/auth/refresh`;
};

export const postAuthRefresh = async (options?: RequestInit): Promise<postAuthRefreshResponse> => {
  return apiFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostAuthRefreshMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError, void, TContext> => {
  const mutationKey = ["postAuthRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, void> = () => {
    return postAuthRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefresh>>
>;

export type PostAuthRefreshMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary アクセストークンのリフレッシュ
 */
export const usePostAuthRefresh = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRefresh>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postAuthRefresh>>, TError, void, TContext> => {
  return useMutation(getPostAuthRefreshMutationOptions(options), queryClient);
};
/**
 * 新しいユーザーを登録する
 * @summary ユーザー登録
 */
export type postAuthRegisterResponse201 = {
  data: GoShishaBackendInternalModelsAuthResponse;
  status: 201;
};

export type postAuthRegisterResponse400 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 400;
};

export type postAuthRegisterResponse409 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 409;
};

export type postAuthRegisterResponse500 = {
  data: GoShishaBackendInternalModelsErrorResponse;
  status: 500;
};

export type postAuthRegisterResponseSuccess = postAuthRegisterResponse201 & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (
  | postAuthRegisterResponse400
  | postAuthRegisterResponse409
  | postAuthRegisterResponse500
) & {
  headers: Headers;
};

export type postAuthRegisterResponse =
  | postAuthRegisterResponseSuccess
  | postAuthRegisterResponseError;

export const getPostAuthRegisterUrl = () => {
  return `/auth/register`;
};

export const postAuthRegister = async (
  goShishaBackendInternalModelsCreateUserInput: GoShishaBackendInternalModelsCreateUserInput,
  options?: RequestInit
): Promise<postAuthRegisterResponse> => {
  return apiFetch<postAuthRegisterResponse>(getPostAuthRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(goShishaBackendInternalModelsCreateUserInput),
  });
};

export const getPostAuthRegisterMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: GoShishaBackendInternalModelsCreateUserInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: GoShishaBackendInternalModelsCreateUserInput },
  TContext
> => {
  const mutationKey = ["postAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: GoShishaBackendInternalModelsCreateUserInput }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = GoShishaBackendInternalModelsCreateUserInput;
export type PostAuthRegisterMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ユーザー登録
 */
export const usePostAuthRegister = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRegister>>,
      TError,
      { data: GoShishaBackendInternalModelsCreateUserInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: GoShishaBackendInternalModelsCreateUserInput },
  TContext
> => {
  return useMutation(getPostAuthRegisterMutationOptions(options), queryClient);
};
