/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { apiFetch } from "../lib/api-client";
import type {
  GoShishaBackendInternalModelsAuthResponse,
  GoShishaBackendInternalModelsCreateUserInput,
  GoShishaBackendInternalModelsErrorResponse,
  GoShishaBackendInternalModelsLoginInput,
  PostAuthLogout200,
  PostAuthRefresh200,
} from "./model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * メールアドレスとパスワードでログインし、JWT（Cookie）を発行する
 * @summary ログイン
 */
export const postAuthLogin = (
  goShishaBackendInternalModelsLoginInput: GoShishaBackendInternalModelsLoginInput,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsAuthResponse>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: goShishaBackendInternalModelsLoginInput,
      signal,
    },
    options
  );
};

export const getPostAuthLoginMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: GoShishaBackendInternalModelsLoginInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: GoShishaBackendInternalModelsLoginInput },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: GoShishaBackendInternalModelsLoginInput }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>;
export type PostAuthLoginMutationBody = GoShishaBackendInternalModelsLoginInput;
export type PostAuthLoginMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ログイン
 */
export const usePostAuthLogin = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data: GoShishaBackendInternalModelsLoginInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: GoShishaBackendInternalModelsLoginInput },
  TContext
> => {
  const mutationOptions = getPostAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Cookieを削除し、Refresh Tokenを無効化する
 * @summary ログアウト
 */
export const postAuthLogout = (
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<PostAuthLogout200>({ url: `/auth/logout`, method: "POST", signal }, options);
};

export const getPostAuthLogoutMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationKey = ["postAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
    return postAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>;

export type PostAuthLogoutMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ログアウト
 */
export const usePostAuthLogout = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationOptions = getPostAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 認証されたユーザーの情報を取得する
 * @summary 現在のユーザー情報取得
 */
export const getAuthMe = (options?: SecondParameter<typeof apiFetch>, signal?: AbortSignal) => {
  return apiFetch<GoShishaBackendInternalModelsAuthResponse>(
    { url: `/auth/me`, method: "GET", signal },
    options
  );
};

export const getGetAuthMeQueryKey = () => {
  return [`/auth/me`] as const;
};

export const getGetAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) =>
    getAuthMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>;
export type GetAuthMeQueryError = GoShishaBackendInternalModelsErrorResponse;

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 現在のユーザー情報取得
 */

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GoShishaBackendInternalModelsErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Refresh Tokenを使って新しいAccess Tokenを発行する
 * @summary アクセストークンのリフレッシュ
 */
export const postAuthRefresh = (
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<PostAuthRefresh200>({ url: `/auth/refresh`, method: "POST", signal }, options);
};

export const getPostAuthRefreshMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError, void, TContext> => {
  const mutationKey = ["postAuthRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, void> = () => {
    return postAuthRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefresh>>
>;

export type PostAuthRefreshMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary アクセストークンのリフレッシュ
 */
export const usePostAuthRefresh = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRefresh>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postAuthRefresh>>, TError, void, TContext> => {
  const mutationOptions = getPostAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 新しいユーザーを登録する
 * @summary ユーザー登録
 */
export const postAuthRegister = (
  goShishaBackendInternalModelsCreateUserInput: GoShishaBackendInternalModelsCreateUserInput,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsAuthResponse>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: goShishaBackendInternalModelsCreateUserInput,
      signal,
    },
    options
  );
};

export const getPostAuthRegisterMutationOptions = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: GoShishaBackendInternalModelsCreateUserInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: GoShishaBackendInternalModelsCreateUserInput },
  TContext
> => {
  const mutationKey = ["postAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: GoShishaBackendInternalModelsCreateUserInput }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = GoShishaBackendInternalModelsCreateUserInput;
export type PostAuthRegisterMutationError = GoShishaBackendInternalModelsErrorResponse;

/**
 * @summary ユーザー登録
 */
export const usePostAuthRegister = <
  TError = GoShishaBackendInternalModelsErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRegister>>,
      TError,
      { data: GoShishaBackendInternalModelsCreateUserInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: GoShishaBackendInternalModelsCreateUserInput },
  TContext
> => {
  const mutationOptions = getPostAuthRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
