/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { apiFetch } from "../lib/api-client";
import type {
  GoShishaBackendInternalModelsFlavor,
  GoShishaBackendInternalModelsServerError,
} from "./model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 全てのフレーバーの一覧を取得します
 * @summary フレーバー一覧取得
 */
export type getFlavorsResponse200 = {
  data: GoShishaBackendInternalModelsFlavor[];
  status: 200;
};

export type getFlavorsResponse500 = {
  data: GoShishaBackendInternalModelsServerError;
  status: 500;
};

export type getFlavorsResponseSuccess = getFlavorsResponse200 & {
  headers: Headers;
};
export type getFlavorsResponseError = getFlavorsResponse500 & {
  headers: Headers;
};

export type getFlavorsResponse = getFlavorsResponseSuccess | getFlavorsResponseError;

export const getGetFlavorsUrl = () => {
  return `/flavors`;
};

export const getFlavors = async (options?: RequestInit): Promise<getFlavorsResponse> => {
  return apiFetch<getFlavorsResponse>(getGetFlavorsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFlavorsQueryKey = () => {
  return [`/flavors`] as const;
};

export const getGetFlavorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFlavors>>,
  TError = GoShishaBackendInternalModelsServerError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlavors>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFlavorsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlavors>>> = ({ signal }) =>
    getFlavors({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFlavors>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFlavorsQueryResult = NonNullable<Awaited<ReturnType<typeof getFlavors>>>;
export type GetFlavorsQueryError = GoShishaBackendInternalModelsServerError;

export function useGetFlavors<
  TData = Awaited<ReturnType<typeof getFlavors>>,
  TError = GoShishaBackendInternalModelsServerError,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlavors>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlavors>>,
          TError,
          Awaited<ReturnType<typeof getFlavors>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFlavors<
  TData = Awaited<ReturnType<typeof getFlavors>>,
  TError = GoShishaBackendInternalModelsServerError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlavors>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlavors>>,
          TError,
          Awaited<ReturnType<typeof getFlavors>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFlavors<
  TData = Awaited<ReturnType<typeof getFlavors>>,
  TError = GoShishaBackendInternalModelsServerError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlavors>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary フレーバー一覧取得
 */

export function useGetFlavors<
  TData = Awaited<ReturnType<typeof getFlavors>>,
  TError = GoShishaBackendInternalModelsServerError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlavors>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFlavorsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
