/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { apiFetch } from "../lib/api-client";
import type {
  GetPosts500,
  GetPostsId400,
  GetPostsId404,
  GoShishaBackendInternalModelsCreatePostInput,
  GoShishaBackendInternalModelsPost,
  GoShishaBackendInternalModelsPostsResponse,
  PostPosts400,
  PostPosts401,
  PostPosts500,
  PostPostsIdLike400,
  PostPostsIdLike404,
  PostPostsIdUnlike400,
  PostPostsIdUnlike404,
} from "./model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 全ての投稿の一覧を取得します（総数付き）
 * @summary 投稿一覧取得
 */
export type getPostsResponse200 = {
  data: GoShishaBackendInternalModelsPostsResponse;
  status: 200;
};

export type getPostsResponse500 = {
  data: GetPosts500;
  status: 500;
};

export type getPostsResponseSuccess = getPostsResponse200 & {
  headers: Headers;
};
export type getPostsResponseError = getPostsResponse500 & {
  headers: Headers;
};

export type getPostsResponse = getPostsResponseSuccess | getPostsResponseError;

export const getGetPostsUrl = () => {
  return `/posts`;
};

export const getPosts = async (options?: RequestInit): Promise<getPostsResponse> => {
  return apiFetch<getPostsResponse>(getGetPostsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPostsQueryKey = () => {
  return [`/posts`] as const;
};

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = GetPosts500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) =>
    getPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type GetPostsQueryError = GetPosts500;

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 投稿一覧取得
 */

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 新しい投稿を作成します（認証必須）。注意: slides内のflavor_idが無効な場合、そのスライドはFlavorなしで作成されます（エラーにはなりません）
 * @summary 投稿作成
 */
export type postPostsResponse201 = {
  data: GoShishaBackendInternalModelsPost;
  status: 201;
};

export type postPostsResponse400 = {
  data: PostPosts400;
  status: 400;
};

export type postPostsResponse401 = {
  data: PostPosts401;
  status: 401;
};

export type postPostsResponse500 = {
  data: PostPosts500;
  status: 500;
};

export type postPostsResponseSuccess = postPostsResponse201 & {
  headers: Headers;
};
export type postPostsResponseError = (
  | postPostsResponse400
  | postPostsResponse401
  | postPostsResponse500
) & {
  headers: Headers;
};

export type postPostsResponse = postPostsResponseSuccess | postPostsResponseError;

export const getPostPostsUrl = () => {
  return `/posts`;
};

export const postPosts = async (
  goShishaBackendInternalModelsCreatePostInput: GoShishaBackendInternalModelsCreatePostInput,
  options?: RequestInit
): Promise<postPostsResponse> => {
  return apiFetch<postPostsResponse>(getPostPostsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(goShishaBackendInternalModelsCreatePostInput),
  });
};

export const getPostPostsMutationOptions = <
  TError = PostPosts400 | PostPosts401 | PostPosts500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPosts>>,
    TError,
    { data: GoShishaBackendInternalModelsCreatePostInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: GoShishaBackendInternalModelsCreatePostInput },
  TContext
> => {
  const mutationKey = ["postPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPosts>>,
    { data: GoShishaBackendInternalModelsCreatePostInput }
  > = (props) => {
    const { data } = props ?? {};

    return postPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsMutationResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>;
export type PostPostsMutationBody = GoShishaBackendInternalModelsCreatePostInput;
export type PostPostsMutationError = PostPosts400 | PostPosts401 | PostPosts500;

/**
 * @summary 投稿作成
 */
export const usePostPosts = <
  TError = PostPosts400 | PostPosts401 | PostPosts500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPosts>>,
      TError,
      { data: GoShishaBackendInternalModelsCreatePostInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: GoShishaBackendInternalModelsCreatePostInput },
  TContext
> => {
  return useMutation(getPostPostsMutationOptions(options), queryClient);
};
/**
 * 指定されたIDの投稿情報を取得します
 * @summary 投稿詳細取得
 */
export type getPostsIdResponse200 = {
  data: GoShishaBackendInternalModelsPost;
  status: 200;
};

export type getPostsIdResponse400 = {
  data: GetPostsId400;
  status: 400;
};

export type getPostsIdResponse404 = {
  data: GetPostsId404;
  status: 404;
};

export type getPostsIdResponseSuccess = getPostsIdResponse200 & {
  headers: Headers;
};
export type getPostsIdResponseError = (getPostsIdResponse400 | getPostsIdResponse404) & {
  headers: Headers;
};

export type getPostsIdResponse = getPostsIdResponseSuccess | getPostsIdResponseError;

export const getGetPostsIdUrl = (id: number) => {
  return `/posts/${id}`;
};

export const getPostsId = async (
  id: number,
  options?: RequestInit
): Promise<getPostsIdResponse> => {
  return apiFetch<getPostsIdResponse>(getGetPostsIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetPostsIdQueryKey = (id: number) => {
  return [`/posts/${id}`] as const;
};

export const getGetPostsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsId>>> = ({ signal }) =>
    getPostsId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsId>>>;
export type GetPostsIdQueryError = GetPostsId400 | GetPostsId404;

export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsId>>,
          TError,
          Awaited<ReturnType<typeof getPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsId>>,
          TError,
          Awaited<ReturnType<typeof getPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 投稿詳細取得
 */

export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 指定された投稿にいいねを追加します
 * @summary 投稿にいいね
 */
export type postPostsIdLikeResponse200 = {
  data: GoShishaBackendInternalModelsPost;
  status: 200;
};

export type postPostsIdLikeResponse400 = {
  data: PostPostsIdLike400;
  status: 400;
};

export type postPostsIdLikeResponse404 = {
  data: PostPostsIdLike404;
  status: 404;
};

export type postPostsIdLikeResponseSuccess = postPostsIdLikeResponse200 & {
  headers: Headers;
};
export type postPostsIdLikeResponseError = (
  | postPostsIdLikeResponse400
  | postPostsIdLikeResponse404
) & {
  headers: Headers;
};

export type postPostsIdLikeResponse = postPostsIdLikeResponseSuccess | postPostsIdLikeResponseError;

export const getPostPostsIdLikeUrl = (id: number) => {
  return `/posts/${id}/like`;
};

export const postPostsIdLike = async (
  id: number,
  options?: RequestInit
): Promise<postPostsIdLikeResponse> => {
  return apiFetch<postPostsIdLikeResponse>(getPostPostsIdLikeUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getPostPostsIdLikeMutationOptions = <
  TError = PostPostsIdLike400 | PostPostsIdLike404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostsIdLike>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostsIdLike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["postPostsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostsIdLike>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return postPostsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostsIdLike>>
>;

export type PostPostsIdLikeMutationError = PostPostsIdLike400 | PostPostsIdLike404;

/**
 * @summary 投稿にいいね
 */
export const usePostPostsIdLike = <
  TError = PostPostsIdLike400 | PostPostsIdLike404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostsIdLike>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPostsIdLike>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getPostPostsIdLikeMutationOptions(options), queryClient);
};
/**
 * 指定された投稿のいいねを取り消します
 * @summary 投稿のいいねを取り消す
 */
export type postPostsIdUnlikeResponse200 = {
  data: GoShishaBackendInternalModelsPost;
  status: 200;
};

export type postPostsIdUnlikeResponse400 = {
  data: PostPostsIdUnlike400;
  status: 400;
};

export type postPostsIdUnlikeResponse404 = {
  data: PostPostsIdUnlike404;
  status: 404;
};

export type postPostsIdUnlikeResponseSuccess = postPostsIdUnlikeResponse200 & {
  headers: Headers;
};
export type postPostsIdUnlikeResponseError = (
  | postPostsIdUnlikeResponse400
  | postPostsIdUnlikeResponse404
) & {
  headers: Headers;
};

export type postPostsIdUnlikeResponse =
  | postPostsIdUnlikeResponseSuccess
  | postPostsIdUnlikeResponseError;

export const getPostPostsIdUnlikeUrl = (id: number) => {
  return `/posts/${id}/unlike`;
};

export const postPostsIdUnlike = async (
  id: number,
  options?: RequestInit
): Promise<postPostsIdUnlikeResponse> => {
  return apiFetch<postPostsIdUnlikeResponse>(getPostPostsIdUnlikeUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getPostPostsIdUnlikeMutationOptions = <
  TError = PostPostsIdUnlike400 | PostPostsIdUnlike404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostsIdUnlike>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostsIdUnlike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["postPostsIdUnlike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostsIdUnlike>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return postPostsIdUnlike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsIdUnlikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostsIdUnlike>>
>;

export type PostPostsIdUnlikeMutationError = PostPostsIdUnlike400 | PostPostsIdUnlike404;

/**
 * @summary 投稿のいいねを取り消す
 */
export const usePostPostsIdUnlike = <
  TError = PostPostsIdUnlike400 | PostPostsIdUnlike404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostsIdUnlike>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPostsIdUnlike>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getPostPostsIdUnlikeMutationOptions(options), queryClient);
};
