/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Go-Shisha API
 * シーシャSNSアプリケーションのバックエンドAPI
このAPIはシーシャの投稿、ユーザー管理を行います
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { apiFetch } from "../lib/api-client";
import type {
  GetPosts500,
  GetPostsId400,
  GetPostsId404,
  GoShishaBackendInternalModelsCreatePostInput,
  GoShishaBackendInternalModelsPost,
  GoShishaBackendInternalModelsPostsResponse,
  PostPosts400,
  PostPostsIdLike400,
  PostPostsIdLike404,
  PostPostsIdUnlike400,
  PostPostsIdUnlike404,
} from "./model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 全ての投稿の一覧を取得します（総数付き）
 * @summary 投稿一覧取得
 */
export const getPosts = (options?: SecondParameter<typeof apiFetch>, signal?: AbortSignal) => {
  return apiFetch<GoShishaBackendInternalModelsPostsResponse>(
    { url: `/posts`, method: "GET", signal },
    options
  );
};

export const getGetPostsQueryKey = () => {
  return [`/posts`] as const;
};

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = GetPosts500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) =>
    getPosts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type GetPostsQueryError = GetPosts500;

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 投稿一覧取得
 */

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts500>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 新しい投稿を作成します
 * @summary 投稿作成
 */
export const postPosts = (
  goShishaBackendInternalModelsCreatePostInput: GoShishaBackendInternalModelsCreatePostInput,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsPost>(
    {
      url: `/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: goShishaBackendInternalModelsCreatePostInput,
      signal,
    },
    options
  );
};

export const getPostPostsMutationOptions = <TError = PostPosts400, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPosts>>,
    TError,
    { data: GoShishaBackendInternalModelsCreatePostInput },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: GoShishaBackendInternalModelsCreatePostInput },
  TContext
> => {
  const mutationKey = ["postPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPosts>>,
    { data: GoShishaBackendInternalModelsCreatePostInput }
  > = (props) => {
    const { data } = props ?? {};

    return postPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsMutationResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>;
export type PostPostsMutationBody = GoShishaBackendInternalModelsCreatePostInput;
export type PostPostsMutationError = PostPosts400;

/**
 * @summary 投稿作成
 */
export const usePostPosts = <TError = PostPosts400, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPosts>>,
      TError,
      { data: GoShishaBackendInternalModelsCreatePostInput },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: GoShishaBackendInternalModelsCreatePostInput },
  TContext
> => {
  const mutationOptions = getPostPostsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 指定されたIDの投稿情報を取得します
 * @summary 投稿詳細取得
 */
export const getPostsId = (
  id: number,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsPost>(
    { url: `/posts/${id}`, method: "GET", signal },
    options
  );
};

export const getGetPostsIdQueryKey = (id?: number) => {
  return [`/posts/${id}`] as const;
};

export const getGetPostsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsId>>> = ({ signal }) =>
    getPostsId(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsId>>>;
export type GetPostsIdQueryError = GetPostsId400 | GetPostsId404;

export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsId>>,
          TError,
          Awaited<ReturnType<typeof getPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsId>>,
          TError,
          Awaited<ReturnType<typeof getPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 投稿詳細取得
 */

export function useGetPostsId<
  TData = Awaited<ReturnType<typeof getPostsId>>,
  TError = GetPostsId400 | GetPostsId404,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsId>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 指定された投稿にいいねを追加します
 * @summary 投稿にいいね
 */
export const postPostsIdLike = (
  id: number,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsPost>(
    { url: `/posts/${id}/like`, method: "POST", signal },
    options
  );
};

export const getPostPostsIdLikeMutationOptions = <
  TError = PostPostsIdLike400 | PostPostsIdLike404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostsIdLike>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostsIdLike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["postPostsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostsIdLike>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return postPostsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostsIdLike>>
>;

export type PostPostsIdLikeMutationError = PostPostsIdLike400 | PostPostsIdLike404;

/**
 * @summary 投稿にいいね
 */
export const usePostPostsIdLike = <
  TError = PostPostsIdLike400 | PostPostsIdLike404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostsIdLike>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPostsIdLike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getPostPostsIdLikeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 指定された投稿のいいねを取り消します
 * @summary 投稿のいいねを取り消す
 */
export const postPostsIdUnlike = (
  id: number,
  options?: SecondParameter<typeof apiFetch>,
  signal?: AbortSignal
) => {
  return apiFetch<GoShishaBackendInternalModelsPost>(
    { url: `/posts/${id}/unlike`, method: "POST", signal },
    options
  );
};

export const getPostPostsIdUnlikeMutationOptions = <
  TError = PostPostsIdUnlike400 | PostPostsIdUnlike404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostsIdUnlike>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostsIdUnlike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["postPostsIdUnlike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostsIdUnlike>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return postPostsIdUnlike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsIdUnlikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostsIdUnlike>>
>;

export type PostPostsIdUnlikeMutationError = PostPostsIdUnlike400 | PostPostsIdUnlike404;

/**
 * @summary 投稿のいいねを取り消す
 */
export const usePostPostsIdUnlike = <
  TError = PostPostsIdUnlike400 | PostPostsIdUnlike404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostsIdUnlike>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postPostsIdUnlike>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getPostPostsIdUnlikeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
